import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { WoodstockGraphQLClientProvider } from '@/lib/woodstock/client/WoodstockGraphQLClient'
import { CacheUpdatedSubscriptionProvider } from '@/lib/woodstock/subscriptions/cacheUpdatedSubscription'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WoodstockGraphQLClientProvider>
          <CacheUpdatedSubscriptionProvider>
            {children} 
          </CacheUpdatedSubscriptionProvider>
        </WoodstockGraphQLClientProvider>
      </body>
    </html>
  )
}
